export interface ContentGuideItem {
  id: string;
  index: number;
  code: string;
  title: string;
  /** Collapsed card summary */
  summary: string;
  concept: string;
  description: string;
  matchedCaption: string;
  videoDuration: string;
  thumbnail?: string;
  videoUrl?: string;
}

export interface ContentGuideMeta {
  serviceId: string;
  shortLabel: string;
  ctaSubtitle: string;
  listTitle: string;
  guides: ContentGuideItem[];
}

export const CONTENT_GUIDES: Record<string, ContentGuideMeta> = {
  visit: {
    serviceId: "visit",
    shortLabel: "OWM 방문형",
    ctaSubtitle: "OWM 방문형 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "OWM 방문형 콘텐츠 제작 방향",
    guides: [
      {
        id: "visit-01",
        index: 1,
        code: "J-1",
        title: "올영 말고 약국",
        summary: "Olive Young만 가지 말고 약국 가라. 최강 반전 훅.",
        concept: "Olive Young만 가지 말고 약국 가라. 최강 반전 훅.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Want skincare that actually works for your skin? Try a Korean pharmacy instead of Olive Young #korea #koreanskincare #eightpharmacy",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DWBq1eKkYtA/embed/",
      },
      {
        id: "visit-02",
        index: 2,
        code: "J-2",
        title: "POV 약국 발견",
        summary: "POV: 명동에서 약사가 이걸 건네준다. 1인칭 발견 서사.",
        concept: "POV: 명동에서 약사가 이걸 건네준다. 1인칭 발견 서사.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "POV: You found the ULTIMATE shopping stop in Myeongdong! @readyyoungpharmacy_global is the biggest pharmacy in Myeongdong.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DRa-afpEuaT/embed/",
      },
      {
        id: "visit-03",
        index: 3,
        code: "J-3",
        title: "매장 투어",
        summary: "약국이 아니라 뮤지엄. 3층·3000종·공정가·무료 건강측정.",
        concept: "약국이 아니라 뮤지엄. 3층·3000종·공정가·무료 건강측정.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "The biggest pharmacy in Seongsu?! I just discovered the Optimal Wellness Pharmacy Museum and this place is INSANE. 3 floors of skincare",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXMD-sRD6y6/embed/",
      },
      {
        id: "visit-04",
        index: 4,
        code: "J-4",
        title: "여행 저장템",
        summary: "SAVE FOR KOREA TRIP — 한국인이 사는 약국템.",
        concept: "SAVE FOR KOREA TRIP — 한국인이 사는 약국템.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "bestie this place is wild!! MEGA PHACTORY Korea's first warehouse-style pharmacy that just opened this year. Prices much cheaper",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DPTshMpD6YM/embed/",
      },
      {
        id: "visit-05",
        index: 5,
        code: "M-1",
        title: "OWM 플래그십",
        summary: "전 한국 최대 약국 旗艦店. 다국어 매장 소개.",
        concept: "전 한국 최대 약국 旗艦店. 다국어 매장 소개.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "江南這間新開幕的藥局真的太扯了 根本比 Olive Young 還好逛 兩層樓 3000+ 商品 Optima Wellness Museum 是全韓國最大藥局旗艦店 (중문 매장 소개)",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DPRYGn-j7B8/embed/",
      },
      {
        id: "visit-06",
        index: 6,
        code: "M-2",
        title: "지점별 랜드마크",
        summary: "성수·명동·강남·북촌 특색 + 지하철 동선.",
        concept: "성수·명동·강남·북촌 특색 + 지하철 동선.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Still only going to Olive Young in Korea? These 3 wellness spots are where Seoul is actually heading in 2026. Save this before you come",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXwvX-MgQOF/embed/",
      },
      {
        id: "visit-07",
        index: 7,
        code: "M-3",
        title: "투어리스트 편의",
        summary: "다국어 스태프·택스리펀·WOWPASS·테스터.",
        concept: "다국어 스태프·택스리펀·WOWPASS·테스터.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Found a super tourist-friendly pharmacy in Hongdae! Berry New Pharmacy is literally 1 minute from Hongdae Station Exit 8",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXZ0MzAgUmr/embed/",
      },
      {
        id: "visit-08",
        index: 8,
        code: "N-3",
        title: "로컬이 진짜 쓰는 것",
        summary: "locals actually use. 진짜배기 프레임.",
        concept: "locals actually use. 진짜배기 프레임.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "The K-Beauty secret tourists are finally catching on to. Forget duty-free counters — the real skincare gems are found inside Korean pharmacies",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DP2B1e3iTE4/embed/",
      },
      {
        id: "visit-09",
        index: 9,
        code: "D-1",
        title: "코스메슈티컬 트렌드",
        summary: "화장품+의약품=코스메슈티컬 업계 새 대세. 시장 현황 앵커.",
        concept: "화장품+의약품=코스메슈티컬 업계 새 대세. 시장 현황 앵커.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "이른바 약국 뷰티템이 업계의 새 대세. 화장품+의약품 합성어 코스메슈티컬 시장이 전 세계적으로 급성장 중.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DM9GDo1SxVc/embed/",
      },
      {
        id: "visit-10",
        index: 10,
        code: "D-2",
        title: "약국에서만",
        summary: "아무 데서나 못 사고 약국에서만 약사 상담 후 구매. 채널 희소성.",
        concept: "아무 데서나 못 사고 약국에서만 약사 상담 후 구매. 채널 희소성.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#광고 약국 전용 재생크림 REVION. PDRN+EGF 복합. 약국에서만 구매 가능하니 약사님 상담 후 구매 추천.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DWEUi5zEuzH/embed/",
      },
      {
        id: "visit-11",
        index: 11,
        code: "D-3",
        title: "더마 브랜드 클래스",
        summary: "일동제약 본사 뷰티 클래스(리쥬닉). 제조사 신뢰 이식.",
        concept: "일동제약 본사 뷰티 클래스(리쥬닉). 제조사 신뢰 이식.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "일동제약 리쥬닉 본사 뷰티클래스 다녀왔어요. 양재동 본사에서 제품 체험·설명·샘플테스트. 제약회사 제품이라 신뢰감.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXk7G8UE9c2/embed/",
      },
      {
        id: "visit-12",
        index: 12,
        code: "D-4",
        title: "성분 대체 가이드",
        summary: "온얼굴 펴바르기엔 화장품이 더 편할 수 있어요.",
        concept: "온얼굴 펴바르기엔 화장품이 더 편할 수 있어요.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "약국 피부템 vs 동일/유사성분 화장품 정리. 치료목적 콕콕은 약국템",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DU2aQghDz3t/embed/",
      },
    ],
  },
  pharmacist: {
    serviceId: "pharmacist",
    shortLabel: "약사 신뢰형",
    ctaSubtitle: "약사 신뢰형 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "약사 신뢰형 콘텐츠 제작 방향",
    guides: [
      {
        id: "pharmacist-01",
        index: 1,
        code: "N-1",
        title: "약사 추천",
        summary: "약사가 나한테 추천해준 K-beauty.",
        concept: "약사가 나한테 추천해준 K-beauty.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "14 Korean Pharmacy Must-Haves (Expert Edition) NOT only OLIVEYOUNG - by a Korean Pharmacist. Planning a trip to Korea?",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXJVUs1EeVf/embed/",
      },
      {
        id: "pharmacist-02",
        index: 2,
        code: "B-1",
        title: "증상별 연고 매칭",
        summary: "좁쌀→에크린겔/염증성→세비타비·아젤리아/색소→멜라토닝. 가격 표기.",
        concept: "좁쌀→에크린겔/염증성→세비타비·아젤리아/색소→멜라토닝. 가격 표기.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#약국뷰티템 3층파란문약국에 다 있어요! 이지에프새살연고·리쥬비넥스·마데카솔겔·아젤리아·세비타비·멜라토닝·애크논·애크린겔·비판텐",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/C7hEpczp2iT/embed/",
      },
      {
        id: "pharmacist-03",
        index: 3,
        code: "B-2",
        title: "최종 요약본",
        summary: "붉은/염증성 세비타비겔 등 고민별 제품+가격 총망라.",
        concept: "붉은/염증성 세비타비겔 등 고민별 제품+가격 총망라.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "2024 약국 최종 요약본 이것만 보세요. 좁쌀/각질 에크린겔 9000~12000원",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DBTmnoDvTuu/embed/",
      },
      {
        id: "pharmacist-04",
        index: 4,
        code: "B-3",
        title: "헷갈리는 것 정리",
        summary: "의외로 헷갈리는 약국 피부템 저장부터. 증상 아이콘 매칭형.",
        concept: "의외로 헷갈리는 약국 피부템 저장부터. 증상 아이콘 매칭형.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "의외로 헷갈리는 약국 피부템! 저장부터. 화농성 여드름/좁쌀·블랙헤드/기미·색소침착/여드름 흉터 등 증상별 아이콘 매칭.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/C9SN3t3hL_W/embed/",
      },
      {
        id: "pharmacist-05",
        index: 5,
        code: "B-4",
        title: "사용 주의",
        summary: "아젤리아는 얼굴 전체 금지·따가움 주의. 올바른 사용법+금기.",
        concept: "아젤리아는 얼굴 전체 금지·따가움 주의. 올바른 사용법+금기.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "여드름 약국 연고 이거 알고 쓰세요. 아젤리아 크림은 트러블·흔적 관리에 좋지만 따가울 수 있어 얼굴 전체 도포 금지.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DbhS5ZcjfvD/embed/",
      },
      {
        id: "pharmacist-06",
        index: 6,
        code: "C-1",
        title: "비판텐 재발견",
        summary: "겟잇뷰티도 아이크림으로 쓰는 비판텐. 용도 밖 뷰티 활용",
        concept: "겟잇뷰티도 아이크림으로 쓰는 비판텐. 용도 밖 뷰티 활용",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "겟잇뷰티 강희재편에서 비판텐 연고를 아이크림으로 사용. 스테로이드 무첨가라 순함. 상비약으로도 구비.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/BcbE8sRHKdI/embed/",
      },
      {
        id: "pharmacist-07",
        index: 7,
        code: "C-2",
        title: "마데카솔 활용",
        summary: "매일보다 소량 섞어 바르기 추천.",
        concept: "매일보다 소량 섞어 바르기 추천.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "쏘핏약사. 약국에서 제일 많이 찾는 약국연고 3가지. 마데카솔겔은 무항생제·무스테로이드",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/C5vIU65u7JG/embed/",
      },
      {
        id: "pharmacist-08",
        index: 8,
        code: "C-3",
        title: "후시딘 vs 대안",
        summary: "약사가 후시딘보다 극찬하는 연고(바스포·에스로반). 반전 훅.",
        concept: "약사가 후시딘보다 극찬하는 연고(바스포·에스로반). 반전 훅.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "현직 약사가 후시딘·마데카솔보다 훨씬 좋다고 극찬하는 연고. #바스포 #에스로반 #상처 #흉터",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/BwT1VngnX9C/embed/",
      },
    ],
  },
  derma: {
    serviceId: "derma",
    shortLabel: "피부과 연계",
    ctaSubtitle: "피부과 연계 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "피부과 연계 콘텐츠 제작 방향",
    guides: [
      {
        id: "derma-01",
        index: 1,
        code: "K-1",
        title: "바이럴 성분 검증",
        summary: "PDRN 아무거나 아니다 — 분자크기·순도·농도가 관건.",
        concept: "PDRN 아무거나 아니다 — 분자크기·순도·농도가 관건.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "ad I had to try this viral Korean pharmacy PDRN cream! PDRN is a controversial ingredient these days which is why choosing the right one is key",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DSS1G04jG-V/embed/",
      },
      {
        id: "derma-02",
        index: 2,
        code: "K-2",
        title: "시술 후 그 크림",
        summary: "강남 병의원 시술 후 발라주는 PDRN 크림. 의료 등급· 클리닉 연계.",
        concept: "강남 병의원 시술 후 발라주는 PDRN 크림. 의료 등급· 클리닉 연계.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Meet Advanced PDRN Rejuvenating Cream. PDRN (Sodium DNA) — the same skin-regenerating ingredient used in dermatology clinics",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DU5zSENjEfT/embed/",
      },
      {
        id: "derma-03",
        index: 3,
        code: "K-3",
        title: "글로우 비포/애프터",
        summary: "The glow is real. 물광·탄력 시각 증명.",
        concept: "The glow is real. 물광·탄력 시각 증명.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "14 hours in an airplane will literally destroy your skin and body... UNLESS you have this! The glow before & after",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DZDCr_akklH/embed/",
      },
      {
        id: "derma-04",
        index: 4,
        code: "K-4",
        title: "PDLLA·콜라겐 확장",
        summary: "스피큘·PDLLA·필러크림 등 안티에이징.",
        concept: "스피큘·PDLLA·필러크림 등 안티에이징.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Neck wrinkles! Smile lines! Losing firmness? Meet the new anti-aging cream from PHARMAtique with Spicules + PDLLA + collagen",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DZoR1kLCZwq/embed/",
      },
      {
        id: "derma-05",
        index: 5,
        code: "N-2",
        title: "피부과 의사 리뷰",
        summary: "서양 더마 인플루언서 성분 리뷰. 서구권 신뢰 이식.",
        concept: "서양 더마 인플루언서 성분 리뷰. 서구권 신뢰 이식.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "The most viral PDRN cream in Korea sold out across pharmacies and recommended by dermatologists - Dr. Reju-All Advanced PDRN Cream",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DU5dCrXjPyg/embed/",
      },
      {
        id: "derma-06",
        index: 6,
        code: "A-1",
        title: "리쥬란 대체템",
        summary: "피부과 리쥬란 성분과 동일한 약국 품절대란템(리쥬비넥스). 시술 다운그레이드 프레임.",
        concept: "피부과 리쥬란 성분과 동일한 약국 품절대란템(리쥬비넥스). 시술 다운그레이드 프레임.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "📌약국에서 이게 보이면 꼭 사세요 ✅리쥬비넥스 피부과 시술로 유명한 리쥬란 아시죠? 그 리쥬란 성분과 동일해서 리쥬란 크림으로 잘 알려진 약국 품절 대란템.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/C4Hx7IHpd2g/embed/",
      },
      {
        id: "derma-07",
        index: 7,
        code: "A-2",
        title: "PDRN+EGF 복합",
        summary: "재생크림은 PDRN/EGF 복합인지 확인(리쥬올·REVION). 성분 조합 교육.",
        concept: "재생크림은 PDRN/EGF 복합인지 확인(리쥬올·REVION). 성분 조합 교육.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#광고 요즘 피부관리는? 약국템 약국 꿀템 TOP3! TOP1. 레비온 재생크림 PDRN+EGF 복합 제형이라 속건조와 겉피부 모두 도와줘요.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DWgcBubk44G/embed/",
      },
      {
        id: "derma-08",
        index: 8,
        code: "A-3",
        title: "재생템 총정리",
        summary: "약국 재생템 2.0 내돈내산(덱스판테놀+연고 꿀조합). 정보성·품절 대안.",
        concept: "약국 재생템 2.0 내돈내산(덱스판테놀+연고 꿀조합). 정보성·품절 대안.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "약국 재생템 버전2.0 정리본 광고x 협찬x 내돈내산o. 피부재생은 피부결·톤·장벽·수분·주름·탄력 모두와 연결. 덱스판테놀+연고 꿀조합.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/C1mGICbpTet/embed/",
      },
      {
        id: "derma-09",
        index: 9,
        code: "A-4",
        title: "ppm 고함량",
        summary: "연어 유래 PDRN 15000ppm+바쿠치올·시카(리쥬닉). 수치로 신뢰.",
        concept: "연어 유래 PDRN 15000ppm+바쿠치올·시카(리쥬닉). 수치로 신뢰.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "일동제약 리쥬닉 뷰티 클래스. 선물로 받은 PDRN 15000ppm 크림. 알래스카 연어 유래 PDRN 고함량 재생 크림 신뢰도 200%.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DXdt_hnkeHO/embed/",
      },
    ],
  },
  seeding: {
    serviceId: "seeding",
    shortLabel: "시딩",
    ctaSubtitle: "시딩 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "시딩 콘텐츠 제작 방향",
    guides: [
      {
        id: "seeding-01",
        index: 1,
        code: "L-1",
        title: "글로벌 리테일 입점",
        summary: "이제 Amazon·ULTA·Boots에서.",
        concept: "이제 Amazon·ULTA·Boots에서.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Huge news. Dr.Reju-All has officially launched at ULTA Beauty. Our bestsellers are now available bringing Korean pharmacy skincare closer",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DZkMCyovMPM/embed/",
      },
      {
        id: "seeding-02",
        index: 2,
        code: "L-2",
        title: "댓글 LINK 유도",
        summary: "댓글에 LINK 남기면 DM으로. 리드 확보.",
        concept: "댓글에 LINK 남기면 DM으로. 리드 확보.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Do not let your dehydrated lines become permanent wrinkles. I used PDRN from @rejuall_official. Comment with skin care and I'll send tips",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DV30--MDMga/embed/",
      },
      {
        id: "seeding-03",
        index: 3,
        code: "L-3",
        title: "가격 정당화",
        summary: "온라인은 좀 비싸도 한국행 비행기값보단 싸잖아.",
        concept: "온라인은 좀 비싸도 한국행 비행기값보단 싸잖아.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "It's a bit pricey online but cheaper than a flight to Korea - u can buy it at local pharmacies for approx. $26 / 35000 KRW",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DKF9zmHhsKZ/embed/",
      },
      {
        id: "seeding-04",
        index: 4,
        code: "L-4",
        title: "세일·재입고",
        summary: "50% off / finally in stock. 긴급성.",
        concept: "50% off / finally in stock. 긴급성.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "Our Advanced PDRN Rejuvenating Cream 20ml is finally back in stock on Amazon! Thank you so much for waiting",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DRKBp1-D3-m/embed/",
      },
      {
        id: "seeding-05",
        index: 5,
        code: "E-1",
        title: "클렌징·토너패드",
        summary: "나이아신아마이드 5% 데일리 케어.",
        concept: "나이아신아마이드 5% 데일리 케어.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "댓글이벤트 #광고. 매일 부담 없이 쓰는 모공 토너패드. 레티날 성분 턴오버 케어",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DbxsMjmzoC5/embed/",
      },
      {
        id: "seeding-06",
        index: 6,
        code: "E-2",
        title: "모공·피지",
        summary: "여름 피지·모공 토너. 계절 훅.",
        concept: "여름 피지·모공 토너. 계절 훅.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "내돈내산! 요즘 관리 잘하는 언니들은 올영대신 약국. 약국 뷰티템 중 찐추천 제품만 쏙쏙. 피부타입별 추천 루틴 DM.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DTz320vjzn_/embed/",
      },
      {
        id: "seeding-07",
        index: 7,
        code: "E-3",
        title: "미백·색소",
        summary: "기미·잡티·색소침착 케어. 고민 지목.",
        concept: "기미·잡티·색소침착 케어. 고민 지목.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#광고 색동서울. 기미랑 잡티 때문에 고민이신 분들. 화장으로 가릴수록 두꺼워져서 고민이었는데 드디어 인생 토너.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DbuqJ7pxqzU/embed/",
      },
      {
        id: "seeding-08",
        index: 8,
        code: "E-4",
        title: "자연유래 순정",
        summary: "대마씨(타마누) 크림 민감성 국민크림(유어초이스). 저자극 소구.",
        concept: "대마씨(타마누) 크림 민감성 국민크림(유어초이스). 저자극 소구.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#유어초이스 대마씨 크림? 세라바인 타마누 크림! 대표 피부 난치병 극복 위해 자연유래 성분만으로 만든 민감성 국민크림.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DMdA_CKPCzJ/embed/",
      },
      {
        id: "seeding-09",
        index: 9,
        code: "F-1",
        title: "계절 꿀템 zip",
        summary: "겨울 필수 약국 뷰티 꿀템 모음.zip 저장하고 미리 대비. 시즌 묶음.",
        concept: "겨울 필수 약국 뷰티 꿀템 모음.zip 저장하고 미리 대비. 시즌 묶음.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "겨울에 무조건 필수인 약국 뷰티 꿀템 모음.zip. 효과 좋은 피부관리템만 엄선. 저장하고 미리미리 겨울 대비하쟈.",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DRKDzSdDx3s/embed/",
      },
      {
        id: "seeding-10",
        index: 10,
        code: "F-2",
        title: "상위 1% 프레임",
        summary: "약보다 잘 팔린다는 찐 상위 1% 약국화장품. 희소·인기 훅.",
        concept: "약보다 잘 팔린다는 찐 상위 1% 약국화장품. 희소·인기 훅.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "약국에서 약보다 더 잘 팔린다는 찐 약국 화장품 모음. 효과만큼은 상위1%라는데? #약국화장품 #재생크림 #클렌징폼",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/COzWNTIpn4Q/embed/",
      },
      {
        id: "seeding-11",
        index: 11,
        code: "F-3",
        title: "댓글 이벤트",
        summary: "댓글 남기면 5분께 선물. 협찬 제품 시딩 CTA.",
        concept: "댓글 남기면 5분께 선물. 협찬 제품 시딩 CTA.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "#선물있어요 #댓글이벤트 관리진심녀의 약국 관리템 3가지. 아무 댓글이나 남기면 구매처+스킨부스터 크림 증정!",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/DO8HO6NEknq/embed/",
      },
      {
        id: "seeding-12",
        index: 12,
        code: "F-4",
        title: "친구 공유",
        summary: "친구들한테 공유ㄱㄱ 다같이 약국 쇼핑 가즈아. 공유 확산.",
        concept: "친구들한테 공유ㄱㄱ 다같이 약국 쇼핑 가즈아. 공유 확산.",
        description: "실제 레퍼런스 영상과 매칭 캡션 패턴을 기준으로, 같은 콘셉트의 콘텐츠를 제작할 때 참고하세요.",
        matchedCaption: "약국에서 약보다 더 잘 팔린다는 찐 상위1% 효과내는 #약국화장품 모음. 친구들한테도 공유ㄱㄱ해서 다같이 약국 쇼핑가즈아~!",
        videoDuration: "—",
        videoUrl: "https://www.instagram.com/p/CRTUMg9lNPK/embed/",
      },
    ],
  },
};

export const ANALYZE_STEPS = [
  {
    label: "레퍼런스 추출",
    status: "API에서 레퍼런스 추출 중...",
  },
  {
    label: "캡션 분석",
    status: "캡션 데이터 분석 중...",
  },
  {
    label: "콘셉트 구성",
    status: "콘텐츠 콘셉트 정리 중...",
  },
] as const;

export function isValidGuideServiceId(id: string): boolean {
  return id in CONTENT_GUIDES;
}
