export interface ContentGuideItem {
  id: string;
  index: number;
  title: string;
  /** Collapsed card summary */
  summary: string;
  concept: string;
  description: string;
  matchedCaption: string;
  videoDuration: string;
  thumbnail?: string;
  videoUrl?: string;
}

export interface ContentGuideMeta {
  serviceId: string;
  shortLabel: string;
  ctaSubtitle: string;
  listTitle: string;
  guides: ContentGuideItem[];
}

export const CONTENT_GUIDES: Record<string, ContentGuideMeta> = {
  visit: {
    serviceId: "visit",
    shortLabel: "OWM 방문형",
    ctaSubtitle: "OWM 방문형 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "OWM 방문형 콘텐츠 제작 방향",
    guides: [
      {
        id: "visit-01",
        index: 1,
        title: "올영 말고 약국",
        summary: "Olive Young만 가지 말고 약국 가라. 최강 반전 훅.",
        concept: "Olive Young만 가지 말고 약국 가라. 최강 반전 훅.",
        description: "\"올영 말고 한국 약국 털어왔다\"로 높은 텐션 나레이션\n쇼핑백을 확 꺼내며 시작 (첫 장면에 빠른 움직임)\nOWM 쇼핑백·매장 로고 무조건 노출 — 아래에 제품 깔아서 꽉 차 보이게\n깔끔한 배경, 매대 정면 한 컷\n제품 하나씩 꺼내며 → \"이건 진짜 내 찐템·재구매템·최애템\"으로 마무리\n엔딩 CTA: \"다음에 한국 오면 OWM에서 이거부터\" ",
        matchedCaption: "Want skincare that actually works for your skin? Try a Korean pharmacy instead of Olive Young #korea #koreanskincare #eightpharmacy",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DWBq1eKkYtA/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DWBq1eKkYtA/embed/",
      },
      {
        id: "visit-02",
        index: 2,
        title: "POV 약국 발견",
        summary: "POV: 명동에서 약사가 이걸 건네준다. 1인칭 발견 서사.",
        concept: "POV: 명동에서 약사가 이걸 건네준다. 1인칭 발견 서사.",
        description: "첫 1초 1인칭 자막: \"명동에서 이걸 발견했다면…\"\n손카메라로 매장 입구 → 계산대 → 추천 코너까지 연속 촬영\n약사/직원이 제품 건네는 장면 1컷 (신뢰 포인트)\n\"이 약국만의 이유\" 3가지를 빠르게 나열 (규모·가격·외국인 편의)\n마지막에 OWM 매장 전경 + \"이 장소 저장해두세요\" 유도",
        matchedCaption: "POV: You found the ULTIMATE shopping stop in Myeongdong! @readyyoungpharmacy_global is the biggest pharmacy in Myeongdong.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DRa-afpEuaT/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DRa-afpEuaT/embed/",
      },
      {
        id: "visit-03",
        index: 3,
        title: "매장 투어",
        summary: "약국이 아니라 뮤지엄. 3층·3000종·공정가·무료 건강측정.",
        concept: "약국이 아니라 뮤지엄. 3층·3000종·공정가·무료 건강측정.",
        description: "\"여긴 약국이 아니라 박물관이에요\" 훅으로 시작\n3층·3000종·무료 건강측정 등 숫자는 텍스트 오버레이로 크게\n층별로 5~7초씩만 보여주는 빠른 투어 (지루하지 않게)\n각 층 전환마다 OWM 브랜드 요소가 프레임 안에 들어오게\n마무리: \"한국 여행 필수 스팟\" + 지도 핀/주소 자막",
        matchedCaption: "The biggest pharmacy in Seongsu?! I just discovered the Optimal Wellness Pharmacy Museum and this place is INSANE. 3 floors of skincare",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXMD-sRD6y6/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXMD-sRD6y6/embed/",
      },
      {
        id: "visit-04",
        index: 4,
        title: "여행 저장템",
        summary: "SAVE FOR KOREA TRIP — 한국인이 사는 약국템.",
        concept: "SAVE FOR KOREA TRIP — 한국인이 사는 약국템.",
        description: "\"한국 여행 전 꼭 저장\" 텍스트를 0.5초 안에 띄우기\n한국인이 실제로 사는 약국템 5~7개만 엄선 (너무 많으면 이탈)\n가격·용량 비교 컷 1회 (올영 vs 약국 느낌)\n제품마다 \"한국인이 이걸 사는 이유\" 한 줄씩\n엔딩: OWM 쇼핑백 들고 \"이 약국 북마크해두세요\" ",
        matchedCaption: "bestie this place is wild!! MEGA PHACTORY Korea's first warehouse-style pharmacy that just opened this year. Prices much cheaper",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DPTshMpD6YM/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DPTshMpD6YM/embed/",
      },
      {
        id: "visit-05",
        index: 5,
        title: "OWM 플래그십",
        summary: "전 한국 최대 약국 旗艦店. 다국어 매장 소개.",
        concept: "전 한국 최대 약국 旗艦店. 다국어 매장 소개.",
        description: "다국어 자막(중·영·일)으로 \"전국 최대\" / \"한국 최대\" 강조\n매장 외관 → 입구 → 대형 매대 와이드샷 3컷 구조\n3000+ 품목, 2층 규모 등 숫자는 화면 분할 그래픽\n외국인 관광객 1인칭 시점으로 촬영 (친구에게 보여주는 톤)\n마무리: \"최적 웰니스 박물관 = OWM\" 이름 각인",
        matchedCaption: "江南這間新開幕的藥局真的太扯了 根本比 Olive Young 還好逛 兩層樓 3000+ 商品 Optima Wellness Museum 是全韓國最大藥局旗艦店 (중문 매장 소개)",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DPRYGn-j7B8/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DPRYGn-j7B8/embed/",
      },
      {
        id: "visit-06",
        index: 6,
        title: "지점별 랜드마크",
        summary: "성수·명동·강남·북촌 특색 + 지하철 동선.",
        concept: "성수·명동·강남·북촌 특색 + 지하철 동선.",
        description: "\"아직도 올영만 가?\" 첫 문장으로 관심 끌기\n성수·명동·강남 등 지점 2~3곳만 (너무 많으면 X)\n각 지점마다 \"역에서 몇 분\" + 랜드마크 1개\n지하철 출구 → OWM까지 동선을 3초 타임랩스\n저장 유도: \"2026 서울 웰니스 지도 — 출국 전 저장\" ",
        matchedCaption: "Still only going to Olive Young in Korea? These 3 wellness spots are where Seoul is actually heading in 2026. Save this before you come",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXwvX-MgQOF/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXwvX-MgQOF/embed/",
      },
      {
        id: "visit-07",
        index: 7,
        title: "투어리스트 편의",
        summary: "다국어 스태프·택스리펀·WOWPASS·테스터.",
        concept: "다국어 스태프·택스리펀·WOWPASS·테스터.",
        description: "홍대/명동 등 관광지 1분 거리 훅 (\"역에서 1분\")\n다국어 직원·택스리펀·WOWPASS·테스터 4가지를 아이콘+1초씩\n외국인이 실제로 구매하는 장면 (줄 서 있거나 계산하는 컷)\n언어 걱정 없다는 메시지를 카메라 보며 말하기\n마무리: \"외국인도 편한 OWM — 프로필 링크 / 댓글에 OWM\" ",
        matchedCaption: "Found a super tourist-friendly pharmacy in Hongdae! Berry New Pharmacy is literally 1 minute from Hongdae Station Exit 8",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXZ0MzAgUmr/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXZ0MzAgUmr/embed/",
      },
      {
        id: "visit-08",
        index: 8,
        title: "로컬이 진짜 쓰는 것",
        summary: "locals actually use. 진짜배기 프레임.",
        concept: "locals actually use. 진짜배기 프레임.",
        description: "\"관광객도 드디어 알아챈 K뷰티 비밀\" 톤\n면세점 말고 약국 매대 컷으로 반전\n\"한국인이 실제로 쓰는\" 자막 반복 (신뢰 프레임)\n한국인처럼 고르는 손동작 클로즈업\n엔딩: OWM 매대에서 브랜드 제품 집어 드는 장면 + 구매 CTA",
        matchedCaption: "The K-Beauty secret tourists are finally catching on to. Forget duty-free counters — the real skincare gems are found inside Korean pharmacies",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DP2B1e3iTE4/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DP2B1e3iTE4/embed/",
      },
      {
        id: "visit-09",
        index: 9,
        title: "코스메슈티컬 트렌드",
        summary: "화장품+의약품=코스메슈티컬 업계 새 대세. 시장 현황 앵커.",
        concept: "화장품+의약품=코스메슈티컬 업계 새 대세. 시장 현황 앵커.",
        description: "\"약국 뷰티가 새 트렌드\" — 업계 키워드로 시작\n화장품 vs 코스메슈티컬 차이를 15초 안에 설명\n약국 전용 브랜드 제품을 OWM 매대에서 클로즈업\n그래프/텍스트로 \"시장 성장\" 느낌만 가볍게 (과하지 않게)\n마무리: \"한국인이 사는 곳에서 — OWM\" ",
        matchedCaption: "이른바 약국 뷰티템이 업계의 새 대세. 화장품+의약품 합성어 코스메슈티컬 시장이 전 세계적으로 급성장 중.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DM9GDo1SxVc/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DM9GDo1SxVc/embed/",
      },
      {
        id: "visit-10",
        index: 10,
        title: "약국에서만",
        summary: "아무 데서나 못 사고 약국에서만 약사 상담 후 구매. 채널 희소성.",
        concept: "아무 데서나 못 사고 약국에서만 약사 상담 후 구매. 채널 희소성.",
        description: "\"다른 데선 못 사요\" 훅\n약국에서만 구매 가능한 제품임을 패키지·라벨로 보여주기\n약사 상담 컷 1회 (전문가 추천 느낌)\n온라인/올영에는 없다는 점을 짧게 대비\n마무리: \"OWM에서 물어보세요 — 직원이 안내해줘요\" ",
        matchedCaption: "#광고 약국 전용 재생크림 REVION. PDRN+EGF 복합. 약국에서만 구매 가능하니 약사님 상담 후 구매 추천.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DWEUi5zEuzH/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DWEUi5zEuzH/embed/",
      },
      {
        id: "visit-11",
        index: 11,
        title: "더마 브랜드 클래스",
        summary: "일동제약 본사 뷰티 클래스(리쥬닉). 제조사 신뢰 이식.",
        concept: "일동제약 본사 뷰티 클래스(리쥬닉). 제조사 신뢰 이식.",
        description: "제조사 본사/클래스 방문 브이로그 톤 (\"본사에 다녀왔어요\")\n제품 체험·샘플·설명 장면으로 신뢰 이식\n\"제약회사가 만든 스킨케어\" 한 줄 강조\n깔끔한 실험실/브랜드룸 배경\n마무리: OWM 매대에 진열된 해당 브랜드 전체 샷",
        matchedCaption: "일동제약 리쥬닉 본사 뷰티클래스 다녀왔어요. 양재동 본사에서 제품 체험·설명·샘플테스트. 제약회사 제품이라 신뢰감.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXk7G8UE9c2/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXk7G8UE9c2/embed/",
      },
      {
        id: "visit-12",
        index: 12,
        title: "성분 대체 가이드",
        summary: "온얼굴 펴바르기엔 화장품이 더 편할 수 있어요.",
        concept: "온얼굴 펴바르기엔 화장품이 더 편할 수 있어요.",
        description: "\"약국템 vs 화장품 — 성분 같아도?\" 비교 틀\n증상·목적별로 약국템 vs 화장품 역할 나누기\n표 형태 오버레이로 한눈에 (치료 vs 데일리)\nOWM에서 두 카테고리 모두 고르는 장면\n마무리: \"치료용 → OWM 약국 코너\" ",
        matchedCaption: "약국 피부템 vs 동일/유사성분 화장품 정리. 치료목적 콕콕은 약국템",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DU2aQghDz3t/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DU2aQghDz3t/embed/",
      },
    ],
  },
  pharmacist: {
    serviceId: "pharmacist",
    shortLabel: "약사 신뢰형",
    ctaSubtitle: "약사 신뢰형 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "약사 신뢰형 콘텐츠 제작 방향",
    guides: [
      {
        id: "pharmacist-01",
        index: 1,
        title: "약사 추천",
        summary: "약사가 나한테 추천해준 K-beauty.",
        concept: "약사가 나한테 추천해준 K-beauty.",
        description: "\"한국 약사 추천 — 올영만 가지 마\" 자막\n약사 복장 또는 명찰로 전문가 신원 확실히\n필수템 5~7개만 빠르게 (전문가 에디션)\n각 제품마다 \"약사가 고르는 이유\" 한 줄\n엔딩: \"한국 여행? OWM 약국부터\" ",
        matchedCaption: "14 Korean Pharmacy Must-Haves (Expert Edition) NOT only OLIVEYOUNG - by a Korean Pharmacist. Planning a trip to Korea?",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXJVUs1EeVf/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXJVUs1EeVf/embed/",
      },
      {
        id: "pharmacist-02",
        index: 2,
        title: "증상별 연고 매칭",
        summary: "좁쌀→에크린겔/염증성→세비타비·아젤리아/색소→멜라토닝. 가격 표기.",
        concept: "좁쌀→에크린겔/염증성→세비타비·아젤리아/색소→멜라토닝. 가격 표기.",
        description: "증상 아이콘(좁쌀·염증·색소) 먼저 보여주고 매칭\n\"이 증상이면 이 연고\" 구조로 3~4쌍만\n가격대를 작은 텍스트로 표기 (신뢰+실용)\n약국 매대에서 해당 제품 찾는 손동작\n주의: \"전체 얼굴 바르지 마세요\" 같은 한 줄 디스클레이머",
        matchedCaption: "#약국뷰티템 3층파란문약국에 다 있어요! 이지에프새살연고·리쥬비넥스·마데카솔겔·아젤리아·세비타비·멜라토닝·애크논·애크린겔·비판텐",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/C7hEpczp2iT/media/?size=l",
        videoUrl: "https://www.instagram.com/p/C7hEpczp2iT/embed/",
      },
      {
        id: "pharmacist-03",
        index: 3,
        title: "최종 요약본",
        summary: "붉은/염증성 세비타비겔 등 고민별 제품+가격 총망라.",
        concept: "붉은/염증성 세비타비겔 등 고민별 제품+가격 총망라.",
        description: "\"2024/2025 약국 최종 요약본 — 이것만 보세요\" 훅\n내돈내산·광고X 배지로 신뢰\n고민별 1줄 + 제품명 + 가격 (표 느낌)\n너무 길지 않게 60초 이내 짧게 몰아보기\n저장 유도: \"저장 — 한국 가면 꼭 필요해요\" ",
        matchedCaption: "2024 약국 최종 요약본 이것만 보세요. 좁쌀/각질 에크린겔 9000~12000원",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DBTmnoDvTuu/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DBTmnoDvTuu/embed/",
      },
      {
        id: "pharmacist-04",
        index: 4,
        title: "헷갈리는 것 정리",
        summary: "의외로 헷갈리는 약국 피부템 저장부터. 증상 아이콘 매칭형.",
        concept: "의외로 헷갈리는 약국 피부템 저장부터. 증상 아이콘 매칭형.",
        description: "\"의외로 헷갈리는 약국템\" — 저장부터 유도\n증상별 아이콘 + 잘못 쓰는 사례 1개씩\n전/후보다 \"이렇게 쓰면 안 돼요\" 교정형\n약사 톤 나레이션 (차분·확신)\nOWM에서 올바른 제품 고르는 장면으로 마무리",
        matchedCaption: "의외로 헷갈리는 약국 피부템! 저장부터. 화농성 여드름/좁쌀·블랙헤드/기미·색소침착/여드름 흉터 등 증상별 아이콘 매칭.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/C9SN3t3hL_W/media/?size=l",
        videoUrl: "https://www.instagram.com/p/C9SN3t3hL_W/embed/",
      },
      {
        id: "pharmacist-05",
        index: 5,
        title: "사용 주의",
        summary: "아젤리아는 얼굴 전체 금지·따가움 주의. 올바른 사용법+금기.",
        concept: "아젤리아는 얼굴 전체 금지·따가움 주의. 올바른 사용법+금기.",
        description: "\"이거 알고 쓰세요\" 경고형 훅 (클릭 유도)\n아젤리아 등 따가움·금기 포인트 명확히\n얼굴 전체 도포 X — 부분만 바르는 시연\n용량·횟수 오해 교정 1컷\n엔딩: \"OWM 약사에게 먼저 물어보세요\" ",
        matchedCaption: "여드름 약국 연고 이거 알고 쓰세요. 아젤리아 크림은 트러블·흔적 관리에 좋지만 따가울 수 있어 얼굴 전체 도포 금지.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DbhS5ZcjfvD/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DbhS5ZcjfvD/embed/",
      },
      {
        id: "pharmacist-06",
        index: 6,
        title: "비판텐 재발견",
        summary: "겟잇뷰티도 아이크림으로 쓰는 비판텐. 용도 밖 뷰티 활용",
        concept: "겟잇뷰티도 아이크림으로 쓰는 비판텐. 용도 밖 뷰티 활용",
        description: "\"겟잇뷰티에서도 쓴다\" — 방송 레퍼런스 훅\n비판텐을 아이크림/스킨케어로 쓰는 용도 확장\n스테로이드 무첨가·순함 강조\n상비약으로 집에 둔다는 일상 컷\nOWM 매대에서 비판텐 찾는 장면",
        matchedCaption: "겟잇뷰티 강희재편에서 비판텐 연고를 아이크림으로 사용. 스테로이드 무첨가라 순함. 상비약으로도 구비.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/BcbE8sRHKdI/media/?size=l",
        videoUrl: "https://www.instagram.com/p/BcbE8sRHKdI/embed/",
      },
      {
        id: "pharmacist-07",
        index: 7,
        title: "마데카솔 활용",
        summary: "매일보다 소량 섞어 바르기 추천.",
        concept: "매일보다 소량 섞어 바르기 추천.",
        description: "\"약사가 제일 많이 찾는 연고 3가지\" 리스트형\n마데카솔: 무항생제·무스테로이드 — 짧게 자막\n\"매일보다 소량 섞어\" 사용법 한 줄\n상처·트러블별로 언제 쓰는지\nOWM 약사 추천 코너 배경",
        matchedCaption: "쏘핏약사. 약국에서 제일 많이 찾는 약국연고 3가지. 마데카솔겔은 무항생제·무스테로이드",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/C5vIU65u7JG/media/?size=l",
        videoUrl: "https://www.instagram.com/p/C5vIU65u7JG/embed/",
      },
      {
        id: "pharmacist-08",
        index: 8,
        title: "후시딘 vs 대안",
        summary: "약사가 후시딘보다 극찬하는 연고(바스포·에스로반). 반전 훅.",
        concept: "약사가 후시딘보다 극찬하는 연고(바스포·에스로반). 반전 훅.",
        description: "\"후시딘보다 이게 낫다?\" 반전 훅\n바스포·에스로반 등 대안 연고 클로즈업\n약사가 극찬한다는 3인칭 프레임\n상처·흉터 케어 목적 명확히\n마무리: OWM에서 상담 후 구매",
        matchedCaption: "현직 약사가 후시딘·마데카솔보다 훨씬 좋다고 극찬하는 연고. #바스포 #에스로반 #상처 #흉터",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/BwT1VngnX9C/media/?size=l",
        videoUrl: "https://www.instagram.com/p/BwT1VngnX9C/embed/",
      },
    ],
  },
  derma: {
    serviceId: "derma",
    shortLabel: "피부과 연계",
    ctaSubtitle: "피부과 연계 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "피부과 연계 콘텐츠 제작 방향",
    guides: [
      {
        id: "derma-01",
        index: 1,
        title: "바이럴 성분 검증",
        summary: "PDRN 아무거나 아니다 — 분자크기·순도·농도가 관건.",
        concept: "PDRN 아무거나 아니다 — 분자크기·순도·농도가 관건.",
        description: "\"붓기엔 호박즙? ❌ 한국인은 이거 먹어요 ✅\" 통념 비틀기\n첫 훅: 카메라 보며 손짓으로 끌어당기기\n시각적 매력 확보 (제품 클로즈업 + 뒤 OWM 로고·매대)\n포인트: 틱톡 바이럴 제품을 약국에서 살 수 있다\n\"이건 약국에서만 → OWM에서 찾아\"로 각인",
        matchedCaption: "ad I had to try this viral Korean pharmacy PDRN cream! PDRN is a controversial ingredient these days which is why choosing the right one is key",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DSS1G04jG-V/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DSS1G04jG-V/embed/",
      },
      {
        id: "derma-02",
        index: 2,
        title: "시술 후 그 크림",
        summary: "강남 병의원 시술 후 발라주는 PDRN 크림. 의료 등급· 클리닉 연계.",
        concept: "강남 병의원 시술 후 발라주는 PDRN 크림. 의료 등급· 클리닉 연계.",
        description: "\"시술 후 병원에서 쓰는 그 크림\" 훅\nPDRN·재생 성분 이름 자막 (의료 연계)\n병원/클리닉 전 → 홈케어 후 1컷\n의사·더마 추천 톤 (과장 X)\n엔딩: OWM에서 동일 라인 구매",
        matchedCaption: "Meet Advanced PDRN Rejuvenating Cream. PDRN (Sodium DNA) — the same skin-regenerating ingredient used in dermatology clinics",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DU5zSENjEfT/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DU5zSENjEfT/embed/",
      },
      {
        id: "derma-03",
        index: 3,
        title: "글로우 비포/애프터",
        summary: "The glow is real. 물광·탄력 시각 증명.",
        concept: "The glow is real. 물광·탄력 시각 증명.",
        description: "\"14시간 비행, 피부 망가졌어요 — 근데…\" 스토리 훅\n전(칙칙) → 후(물광) 3초 전후 컷\n제품 바르는 ASMR 느낌 1컷\n과장된 필터 X, 자연광 피부\n마무리: \"회복 루틴 — OWM에서\" ",
        matchedCaption: "14 hours in an airplane will literally destroy your skin and body... UNLESS you have this! The glow before & after",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DZDCr_akklH/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DZDCr_akklH/embed/",
      },
      {
        id: "derma-04",
        index: 4,
        title: "PDLLA·콜라겐 확장",
        summary: "스피큘·PDLLA·필러크림 등 안티에이징.",
        concept: "스피큘·PDLLA·필러크림 등 안티에이징.",
        description: "\"목 주름? 팔자 주름?\" 문제 제기형 오프닝\n스피큘·PDLLA·콜라겐 키워드 텍스트 오버레이\n50+ 타겟이면 또렷한 성숙 피부 모델/손\n안티에이징 텍스처 클로즈업\nOWM 더마 코너에서 제품 라인업",
        matchedCaption: "Neck wrinkles! Smile lines! Losing firmness? Meet the new anti-aging cream from PHARMAtique with Spicules + PDLLA + collagen",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DZoR1kLCZwq/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DZoR1kLCZwq/embed/",
      },
      {
        id: "derma-05",
        index: 5,
        title: "피부과 의사 리뷰",
        summary: "서양 더마 인플루언서 성분 리뷰. 서구권 신뢰 이식.",
        concept: "서양 더마 인플루언서 성분 리뷰. 서구권 신뢰 이식.",
        description: "\"피부과 전문의 추천\" — 전문가 배지\n성분표·임상/논문 언급은 짧게 (신뢰만)\n팩트 위주 톤 (과장 없이)\n품절·약국 추천 스토리 1줄\nOWM 매대 품절/인기 표시 (품절임박 분위기)",
        matchedCaption: "The most viral PDRN cream in Korea sold out across pharmacies and recommended by dermatologists - Dr. Reju-All Advanced PDRN Cream",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DU5dCrXjPyg/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DU5dCrXjPyg/embed/",
      },
      {
        id: "derma-06",
        index: 6,
        title: "리쥬란 대체템",
        summary: "피부과 리쥬란 성분과 동일한 약국 품절대란템(리쥬비넥스). 시술 다운그레이드 프레임.",
        concept: "피부과 리쥬란 성분과 동일한 약국 품절대란템(리쥬비넥스). 시술 다운그레이드 프레임.",
        description: "\"약국에서 이거 보이면 꼭 사세요\" 훅\n리쥬란 시술 → 약국 크림 다운그레이드 프레임\n\"피부과 대신 약국템\" 비교는 과장 없이\n품절대란·재입고 언급으로 희소성\nOWM 매대에서 집어 드는 순간",
        matchedCaption: "📌약국에서 이게 보이면 꼭 사세요 ✅리쥬비넥스 피부과 시술로 유명한 리쥬란 아시죠? 그 리쥬란 성분과 동일해서 리쥬란 크림으로 잘 알려진 약국 품절 대란템.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/C4Hx7IHpd2g/media/?size=l",
        videoUrl: "https://www.instagram.com/p/C4Hx7IHpd2g/embed/",
      },
      {
        id: "derma-07",
        index: 7,
        title: "PDRN+EGF 복합",
        summary: "재생크림은 PDRN/EGF 복합인지 확인(리쥬올·REVION). 성분 조합 교육.",
        concept: "재생크림은 PDRN/EGF 복합인지 확인(리쥬올·REVION). 성분 조합 교육.",
        description: "\"PDRN + EGF — 성분표 확인\" 성분 교육형\n복합 제형 vs 단일 성분 차이 20초\n속건조·장벽·재생 키워드\n손등/볼에 발라보는 텍스처\n약사/더마 추천 코너 배경",
        matchedCaption: "#광고 요즘 피부관리는? 약국템 약국 꿀템 TOP3! TOP1. 레비온 재생크림 PDRN+EGF 복합 제형이라 속건조와 겉피부 모두 도와줘요.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DWgcBubk44G/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DWgcBubk44G/embed/",
      },
      {
        id: "derma-08",
        index: 8,
        title: "재생템 총정리",
        summary: "약국 재생템 2.0 내돈내산(덱스판테놀+연고 꿀조합). 정보성·품절 대안.",
        concept: "약국 재생템 2.0 내돈내산(덱스판테놀+연고 꿀조합). 정보성·품절 대안.",
        description: "\"약국 재생템 2.0 — 광고X 협찬X 내돈내산\" 신뢰 훅\n덱스판테놀+연고 꿀조합 등 2~3개만\n피부결·톤·장벽·수분 연결 설명은 짧게\n표/체크리스트 오버레이\n저장 유도 + OWM에서 한 번에 구매",
        matchedCaption: "약국 재생템 버전2.0 정리본 광고x 협찬x 내돈내산o. 피부재생은 피부결·톤·장벽·수분·주름·탄력 모두와 연결. 덱스판테놀+연고 꿀조합.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/C1mGICbpTet/media/?size=l",
        videoUrl: "https://www.instagram.com/p/C1mGICbpTet/embed/",
      },
      {
        id: "derma-09",
        index: 9,
        title: "ppm 고함량",
        summary: "연어 유래 PDRN 15000ppm+바쿠치올·시카(리쥬닉). 수치로 신뢰.",
        concept: "연어 유래 PDRN 15000ppm+바쿠치올·시카(리쥬닉). 수치로 신뢰.",
        description: "\"15,000ppm PDRN\" — 숫자를 크게\n연어 유래·고함량·제약사 브랜드 3포인트\n본사 클래스/샘플 체험 컷 1회\n신뢰도 200% 같은 감성 한 줄 (과하지 않게)\nOWM 전용 진열 클로즈업",
        matchedCaption: "일동제약 리쥬닉 뷰티 클래스. 선물로 받은 PDRN 15000ppm 크림. 알래스카 연어 유래 PDRN 고함량 재생 크림 신뢰도 200%.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DXdt_hnkeHO/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DXdt_hnkeHO/embed/",
      },
    ],
  },
  seeding: {
    serviceId: "seeding",
    shortLabel: "시딩",
    ctaSubtitle: "시딩 콘텐츠의 제작 방향을 확인해보세요.",
    listTitle: "시딩 콘텐츠 제작 방향",
    guides: [
      {
        id: "seeding-01",
        index: 1,
        title: "글로벌 리테일 입점",
        summary: "이제 Amazon·ULTA·Boots에서.",
        concept: "이제 Amazon·ULTA·Boots에서.",
        description: "\"대박 소식 — ULTA / Amazon / Boots 입점\" 글로벌 훅\n한국 약국 → 해외 리테일 연결 스토리\n브랜드 로고·매장 사진 교차 편집\nK-약국 스킨케어 키워드\n현지에서도 OWM에서 시작했다는 기원 스토리",
        matchedCaption: "Huge news. Dr.Reju-All has officially launched at ULTA Beauty. Our bestsellers are now available bringing Korean pharmacy skincare closer",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DZkMCyovMPM/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DZkMCyovMPM/embed/",
      },
      {
        id: "seeding-02",
        index: 2,
        title: "댓글 LINK 유도",
        summary: "댓글에 LINK 남기면 DM으로. 리드 확보.",
        concept: "댓글에 LINK 남기면 DM으로. 리드 확보.",
        description: "\"댓글에 LINK 달면 리스트 보내드려요\" 훅\n피부 고민 키워드(속건조 잔주름 등)로 공감\n제품 1개만 깊게, DM 유도는 1회\n댓글 수 올리는 질문형 마무리\nOWM에서 구매 가능하다는 한 줄",
        matchedCaption: "Do not let your dehydrated lines become permanent wrinkles. I used PDRN from @rejuall_official. Comment with skin care and I'll send tips",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DV30--MDMga/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DV30--MDMga/embed/",
      },
      {
        id: "seeding-03",
        index: 3,
        title: "가격 정당화",
        summary: "온라인은 좀 비싸도 한국행 비행기값보단 싸잖아.",
        concept: "온라인은 좀 비싸도 한국행 비행기값보단 싸잖아.",
        description: "\"온라인은 비싸지만 — 한국行 비행기값보단 싸요\" 훅\n현지 약국 가격 vs 한국 가격 비교 (대략)\n$26 / 35,000원 같은 구체 숫자\n여행 못 가도 현지 채널 있다는 위로\nOWM 오프라인이 정답이라는 메시지",
        matchedCaption: "It's a bit pricey online but cheaper than a flight to Korea - u can buy it at local pharmacies for approx. $26 / 35000 KRW",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DKF9zmHhsKZ/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DKF9zmHhsKZ/embed/",
      },
      {
        id: "seeding-04",
        index: 4,
        title: "세일·재입고",
        summary: "50% off / finally in stock. 긴급성.",
        concept: "50% off / finally in stock. 긴급성.",
        description: "\"드디어 재입고\" / \"50% 할인\" 긴급성 훅\nAmazon/공식몰 캡처 또는 손들고 기뻐하는 리액션\n기다린 팔로워에게 감사 한 줄\n재입고 알림·한정 수량 분위기\n한국에서는 OWM에서 바로",
        matchedCaption: "Our Advanced PDRN Rejuvenating Cream 20ml is finally back in stock on Amazon! Thank you so much for waiting",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DRKBp1-D3-m/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DRKBp1-D3-m/embed/",
      },
      {
        id: "seeding-05",
        index: 5,
        title: "클렌징·토너패드",
        summary: "나이아신아마이드 5% 데일리 케어.",
        concept: "나이아신아마이드 5% 데일리 케어.",
        description: "메이크업·나이트 루틴에 토너패드 자연 삽입\n나이아신아마이드·레티날 등 성분 1개만\n데일리 부담 없다는 톤\n전후 피부는 과장 X\n\"약국 전용 — OWM에서만\" 한 줄",
        matchedCaption: "댓글이벤트 #광고. 매일 부담 없이 쓰는 모공 토너패드. 레티날 성분 턴오버 케어",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DbxsMjmzoC5/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DbxsMjmzoC5/embed/",
      },
      {
        id: "seeding-06",
        index: 6,
        title: "모공·피지",
        summary: "여름 피지·모공 토너. 계절 훅.",
        concept: "여름 피지·모공 토너. 계절 훅.",
        description: "\"올영 대신 약국\" — 현지어로 현지 톤\n여름 피지·모공 키워드\n피부 타입별 추천 \"DM 주세요\" 유도 가능\n친구 추천처럼 말하기\nOWM 마무리: 한국 방문 시 오프라인 구매",
        matchedCaption: "내돈내산! 요즘 관리 잘하는 언니들은 올영대신 약국. 약국 뷰티템 중 찐추천 제품만 쏙쏙. 피부타입별 추천 루틴 DM.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DTz320vjzn_/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DTz320vjzn_/embed/",
      },
      {
        id: "seeding-07",
        index: 7,
        title: "미백·색소",
        summary: "기미·잡티·색소침착 케어. 고민 지목.",
        concept: "기미·잡티·색소침착 케어. 고민 지목.",
        description: "기미·잡티·색소 고민 짚어주기 (\"이런 고민 있으면…\")\n화장으로 가리기 vs 스킨케어 솔루션 대비\n인생 토너/세럼 1개만\n전은 자연광, 필터 과다 X\nOWM 매대에서 해당 브랜드",
        matchedCaption: "#광고 색동서울. 기미랑 잡티 때문에 고민이신 분들. 화장으로 가릴수록 두꺼워져서 고민이었는데 드디어 인생 토너.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DbuqJ7pxqzU/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DbuqJ7pxqzU/embed/",
      },
      {
        id: "seeding-08",
        index: 8,
        title: "자연유래 순정",
        summary: "대마씨(타마누) 크림 민감성 국민크림(유어초이스). 저자극 소구.",
        concept: "대마씨(타마누) 크림 민감성 국민크림(유어초이스). 저자극 소구.",
        description: "민감성·저자극·자연유래 키워드\n대마씨/타마누 등 성분 스토리 15초\n\"국민크림\" 프레임 — 많이 쓰는 느낌\n패치 테스트 또는 손등 시연\n약국 전용 → OWM",
        matchedCaption: "#유어초이스 대마씨 크림? 세라바인 타마누 크림! 대표 피부 난치병 극복 위해 자연유래 성분만으로 만든 민감성 국민크림.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DMdA_CKPCzJ/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DMdA_CKPCzJ/embed/",
      },
      {
        id: "seeding-09",
        index: 9,
        title: "계절 꿀템 zip",
        summary: "겨울 필수 약국 뷰티 꿀템 모음.zip 저장하고 미리 대비. 시즌 묶음.",
        concept: "겨울 필수 약국 뷰티 꿀템 모음.zip 저장하고 미리 대비. 시즌 묶음.",
        description: "\"겨울 약국 필수템.zip\" — 저장형 훅\n겨울 필수 5~7개 짧게 몰아보기 (빠른 컷)\n\"겨울 전 저장하고 준비\"\n계절 훅으로 시의성\nOWM 쇼핑백/매대 마무리",
        matchedCaption: "겨울에 무조건 필수인 약국 뷰티 꿀템 모음.zip. 효과 좋은 피부관리템만 엄선. 저장하고 미리미리 겨울 대비하쟈.",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DRKDzSdDx3s/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DRKDzSdDx3s/embed/",
      },
      {
        id: "seeding-10",
        index: 10,
        title: "상위 1% 프레임",
        summary: "약보다 잘 팔린다는 찐 상위 1% 약국화장품. 희소·인기 훅.",
        concept: "약보다 잘 팔린다는 찐 상위 1% 약국화장품. 희소·인기 훅.",
        description: "\"약보다 잘 팔린다\" / \"상위 1%\" 훅\n약국 화장품 인기 순위 분위기\n효과 상위 1% — 과장은 피하고 레퍼런스 톤\n3~5개 제품만\n친구 공유 유도: \"한국 여행 갈 친구에게 보내\" ",
        matchedCaption: "약국에서 약보다 더 잘 팔린다는 찐 약국 화장품 모음. 효과만큼은 상위1%라는데? #약국화장품 #재생크림 #클렌징폼",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/COzWNTIpn4Q/media/?size=l",
        videoUrl: "https://www.instagram.com/p/COzWNTIpn4Q/embed/",
      },
      {
        id: "seeding-11",
        index: 11,
        title: "댓글 이벤트",
        summary: "댓글 남기면 5분께 선물. 협찬 제품 시딩 CTA.",
        concept: "댓글 남기면 5분께 선물. 협찬 제품 시딩 CTA.",
        description: "\"아무 댓글 — 5명에게 선물\" 이벤트 훅\n관리템 3가지만 짧게 소개\n협찬 제품 시딩 CTA\n댓글·참여 장면 교차 편집\n구매처 OWM 언급",
        matchedCaption: "#선물있어요 #댓글이벤트 관리진심녀의 약국 관리템 3가지. 아무 댓글이나 남기면 구매처+스킨부스터 크림 증정!",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/DO8HO6NEknq/media/?size=l",
        videoUrl: "https://www.instagram.com/p/DO8HO6NEknq/embed/",
      },
      {
        id: "seeding-12",
        index: 12,
        title: "친구 공유",
        summary: "친구들한테 공유ㄱㄱ 다같이 약국 쇼핑 가즈아. 공유 확산.",
        concept: "친구들한테 공유ㄱㄱ 다같이 약국 쇼핑 가즈아. 공유 확산.",
        description: "\"친구랑 공유 — 약국 쇼핑 가자\" 훅\n상위 1% 효과템 모음 짧게 몰아보기\n친구 태그 유도\n공동 구매·여행 쇼핑 분위기\nOWM을 목적지로 명시",
        matchedCaption: "약국에서 약보다 더 잘 팔린다는 찐 상위1% 효과내는 #약국화장품 모음. 친구들한테도 공유ㄱㄱ해서 다같이 약국 쇼핑가즈아~!",
        videoDuration: "—",
        thumbnail: "https://www.instagram.com/p/CRTUMg9lNPK/media/?size=l",
        videoUrl: "https://www.instagram.com/p/CRTUMg9lNPK/embed/",
      },
    ],
  },
};

export const ANALYZE_STEPS = [
  {
    label: "레퍼런스 추출",
    status: "API에서 레퍼런스 추출 중...",
  },
  {
    label: "캡션 분석",
    status: "캡션 데이터 분석 중...",
  },
  {
    label: "콘셉트 구성",
    status: "콘텐츠 콘셉트 정리 중...",
  },
] as const;

export function isValidGuideServiceId(id: string): boolean {
  return id in CONTENT_GUIDES;
}
