import { Campaign, MyApplication } from "./types";

export const campaigns: Campaign[] = [
  {
    id: "camp-001",
    influencer: {
      name: "화장하는 청담언니",
      handle: "@cookingmua",
      platform: "youtube",
      followers: "182만",
      category: "라이프스타일 / 건강",
      thumbnailUrl: "https://yt3.googleusercontent.com/8D0xYRMWpHCKy6vgNjuzAazEuRKQeYdArJdMBI-iiPIuxhH9ASc4Xrwv2s4yeOXmbYTfCrwg=s400-c-k-c0x00ffffff-no-rj",
      profileUrl: "https://www.youtube.com/@cookingmua",
    },
    contentTitle: "OWM 약국 브이로그 – 건강 루틴 공개",
    contentType: "약국 방문 촬영 브이로그",
    recruitDeadline: "2026-07-01",
    shootingDate: "2026-07-08",
    publishDate: "2026-07-13",
    totalSlots: 5,
    slots: [
      { id: 1, status: "filled", brandName: "뉴트리원" },
      { id: 2, status: "filled", brandName: "에너씨슬" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
      { id: 5, status: "reserved", brandName: "협의 중" },
    ],
    totalCost: 20000000,
    perSlotCost: 4000000,
    contentGuide: [
      "약국 내 제품 자연스러운 픽업 장면 (5~8초 노출)",
      "제품 효능 1줄 멘션 (사전 협의된 스크립트 기반)",
      "영상 말미 브랜드 로고 자막 3초 삽입",
      "인스타그램 스토리 1회 추가 노출 포함",
    ],
    restrictions: [
      "경쟁사 동일 카테고리 브랜드 동시 탑승 불가",
      "의약품, 주류 카테고리 불가",
      "노출 순서는 선착순 신청 기준 배정",
    ],
    status: "open",
    country: "us",
  },
  {
    id: "camp-002",
    influencer: {
      name: "진우와 해티",
      handle: "@JinandHattie",
      platform: "youtube",
      followers: "94만",
      category: "뷰티 / 웰니스",
      thumbnailUrl: "https://yt3.googleusercontent.com/WSL028L6Ogb4s4F3SvKcZ7z_j53_cCu9HLhfWWJ9OdUUhGRtv3PGCYkbo5VJgx2qIycsNM5kGQ=s400-c-k-c0x00ffffff-no-rj",
      profileUrl: "https://www.youtube.com/c/JinandHattie",
    },
    contentTitle: "나의 아침 루틴 – 뷰티&헬스 하울",
    contentType: "모닝루틴 릴스 + 스토리",
    recruitDeadline: "2026-07-03",
    shootingDate: "2026-07-10",
    publishDate: "2026-07-15",
    totalSlots: 4,
    slots: [
      { id: 1, status: "filled", brandName: "이니스프리" },
      { id: 2, status: "available" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
    ],
    totalCost: 12000000,
    perSlotCost: 3000000,
    contentGuide: [
      "아침 스킨케어 루틴 중 제품 사용 장면 (10초 내)",
      "제품명 + 브랜드 태그 스토리 1회",
      "릴스 캡션 브랜드 언급 포함",
    ],
    restrictions: [
      "동일 카테고리 경쟁 브랜드 불가",
      "화장품 4종 이하 노출 가능",
    ],
    status: "open",
    country: "us",
  },
  {
    id: "camp-009",
    influencer: {
      name: "바다",
      handle: "@pada_heli",
      platform: "instagram",
      followers: "100만",
      category: "뷰티 / 라이프스타일",
      thumbnailUrl: "https://scontent-nrt1-1.cdninstagram.com/v/t51.71878-15/497524825_1687303171927436_4834775452833210417_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt1-1.cdninstagram.com&_nc_cat=108&_nc_oc=Q6cZ2gFjGf7ZPEcoEvL83yCRpWJunXyp779mgigao1nir-yWczCU_jWksfZ-iKP513K7Hfo&_nc_ohc=HT9TAjj8mmMQ7kNvwEYlCVU&_nc_gid=8exFK2T0supHEZ-pxq-Yew&edm=ALY_pVYBAAAA&ccb=7-5&oh=00_Af-B-QQTLPDC459rSm3ZHqP1UIUjRyYmfeyv2LbpQYcXtg&oe=6A409945&_nc_sid=57e406",
      profileUrl: "https://www.instagram.com/pada_heli",
    },
    contentTitle: "OWM 신사점 방문 콘텐츠",
    contentType: "릴스 + 스토리",
    recruitDeadline: "2026-06-20",
    shootingDate: "2026-06-25",
    publishDate: "2026-06-30",
    totalSlots: 5,
    slots: [
      { id: 1, status: "filled", brandName: "유이크" },
      { id: 2, status: "filled", brandName: "23yearsold" },
      { id: 3, status: "filled", brandName: "헤브블루" },
      { id: 4, status: "filled", brandName: "닥터리엔장" },
      { id: 5, status: "filled", brandName: "옵티마 이뮨" },
    ],
    totalCost: 10000000,
    perSlotCost: 2000000,
    contentGuide: [
      "컨셉: '옆에 있는 남편도 몰랐던 걸, OWM에서 알았어요' — 남편과 티키타카 케미로 OWM 신사점의 프리미엄 웰니스 경험을 자연스럽게 소개. 외국인 시선으로 공간·상담·제품을 강조하며, 엔딩에서 '옆에 있던 너보다 처음 본 약사님이 날 더 잘 알더라' 대사로 마무리.",
      "유이크 (열감진정 물광세트)",
      "23yearsold (바데카실)",
      "헤브블루 (마스크팩)",
      "닥터리엔장 겔 마스크",
      "옵티마 이뮨",
    ],
    restrictions: [
      "5개 지정 브랜드 외 타 제품 광고 병행 불가",
      "의약품 효능·효과 의학적 표현 및 과장 광고 금지",
      "매장 내 타 브랜드 광고물 노출 금지",
      "광고 표기 필수 (#광고 #협찬 #OWM)",
    ],
    status: "closing",
    country: "us",
  },
  {
    id: "camp-010",
    influencer: {
      name: "Jennifer",
      handle: "@jenniferwohner",
      platform: "instagram",
      followers: "46만",
      category: "뷰티 / 라이프스타일",
      thumbnailUrl: "https://scontent-nrt6-1.cdninstagram.com/v/t51.71878-15/684841662_989122356807979_6164005633872958037_n.jpg?stp=dst-jpg_e15_tt6&_nc_ht=scontent-nrt6-1.cdninstagram.com&_nc_cat=107&_nc_oc=Q6cZ2gHkkk0n3hEan1JUvfE0wSfgq19jXKp-oKhZ-SWGBd3OYYnQtuAzRxFZ51VnTaCiUXc&_nc_ohc=3jcIQgirgC8Q7kNvwH38Ske&_nc_gid=5uHkv9zUVqus_2WO5kHS8Q&edm=ALY_pVYBAAAA&ccb=7-5&oh=00_Af-CRITcCQGc5Yr_3l4EkYTHjfpT43Osnq5sLf4VBpT_rg&oe=6A408D89&_nc_sid=57e406",
      profileUrl: "https://www.instagram.com/jenniferwohner",
    },
    contentTitle: "OWM 신사점 방문 콘텐츠",
    contentType: "릴스 + 스토리",
    recruitDeadline: "2026-06-21",
    shootingDate: "2026-06-28",
    publishDate: "2026-07-03",
    totalSlots: 5,
    slots: [
      { id: 1, status: "filled", brandName: "유이크" },
      { id: 2, status: "filled", brandName: "23yearsold" },
      { id: 3, status: "filled", brandName: "헤브블루" },
      { id: 4, status: "filled", brandName: "닥터리엔장" },
      { id: 5, status: "filled", brandName: "옵티마 이뮨" },
    ],
    totalCost: 10000000,
    perSlotCost: 2000000,
    contentGuide: [
      "컨셉: 남자친구의 시선으로 바라본 OWM — '여자친구가 가자고 해서 따라왔는데, 나도 모르게 진짜 필요한 게 생겼다.' 파트너와 함께하는 OWM 신사점 탐방 콘텐츠. 외국인 커플의 자연스러운 리액션으로 공간·상담·제품의 프리미엄 경험을 전달.",
      "유이크 (열감진정 물광세트)",
      "23yearsold (바데카실)",
      "헤브블루 (마스크팩)",
      "닥터리엔장 겔 마스크",
      "옵티마 이뮨",
    ],
    restrictions: [
      "5개 지정 브랜드 외 타 제품 광고 병행 불가",
      "경쟁 제품 비교 금지",
      "가격 언급 금지",
      "거꾸로/미러 촬영 금지",
      "비판적 표현 금지",
      "광고 표기 필수 (#광고 #협찬 #OWM)",
    ],
    status: "closing",
    country: "us",
  },
  {
    id: "camp-003",
    influencer: {
      name: "흑백리뷰",
      handle: "@흑백리뷰",
      platform: "youtube",
      followers: "340만",
      category: "푸드 / 먹방",
      thumbnailUrl: "https://yt3.googleusercontent.com/IH2MK-J2Xlxzpm7LH6fDtcve-bogZdVKozRtoXKfwX-zRwd9s0QXzKFt9RUjyr9oAI7-FfZF=s400-c-k-c0x00ffffff-no-rj",
      profileUrl: "https://www.youtube.com/@흑백리뷰",
    },
    contentTitle: "편의점 신상 털기 – 7월 PICK",
    contentType: "편의점 하울 + 리뷰",
    recruitDeadline: "2026-06-26",
    shootingDate: "2026-07-03",
    publishDate: "2026-07-08",
    totalSlots: 6,
    slots: [
      { id: 1, status: "filled", brandName: "롯데웰푸드" },
      { id: 2, status: "filled", brandName: "CJ제일제당" },
      { id: 3, status: "filled", brandName: "농심" },
      { id: 4, status: "filled", brandName: "오리온" },
      { id: 5, status: "available" },
      { id: 6, status: "available" },
    ],
    totalCost: 30000000,
    perSlotCost: 5000000,
    contentGuide: [
      "편의점에서 제품 직접 구매 및 시식 장면",
      "맛 평가 + 추천 멘션 (20초~30초)",
      "영상 설명란 브랜드 링크 포함",
      "유튜브 커뮤니티 포스팅 1회",
    ],
    restrictions: [
      "주류/담배 카테고리 불가",
      "동일 식품군 브랜드 2개 이상 불가",
    ],
    status: "closing",
    country: "jp",
  },
  {
    id: "camp-004",
    influencer: {
      name: "핏스타 지수",
      handle: "@fitstar_jisu",
      platform: "tiktok",
      followers: "51만",
      category: "피트니스 / 다이어트",
      thumbnailUrl: "https://i.pravatar.cc/300?img=20",
      profileUrl: "https://i.pravatar.cc/300?img=20",
    },
    contentTitle: "홈트 챌린지 30일 – 필수템 공개",
    contentType: "챌린지 + 제품 리뷰 쇼츠",
    recruitDeadline: "2026-07-13",
    shootingDate: "2026-07-20",
    publishDate: "2026-07-25",
    totalSlots: 3,
    slots: [
      { id: 1, status: "available" },
      { id: 2, status: "available" },
      { id: 3, status: "available" },
    ],
    totalCost: 9000000,
    perSlotCost: 3000000,
    contentGuide: [
      "운동 중 제품 사용/착용 자연스러운 노출",
      "제품 효과 짧은 멘션 (5초 이내)",
      "틱톡 챌린지 태그 + 브랜드 태그",
    ],
    restrictions: ["보충제 2개 이상 탑승 불가", "의약품 불가"],
    status: "open",
    country: "jp",
  },
  {
    id: "camp-005",
    influencer: {
      name: "여행하는 서연",
      handle: "@travel_seoyeon",
      platform: "instagram",
      followers: "128만",
      category: "여행 / 라이프",
      thumbnailUrl: "https://i.pravatar.cc/300?img=25",
      profileUrl: "https://i.pravatar.cc/300?img=25",
    },
    contentTitle: "제주 3박4일 여행 – 나만의 짐 꾸리기",
    contentType: "여행 패킹 + 릴스",
    recruitDeadline: "2026-07-11",
    shootingDate: "2026-07-18",
    publishDate: "2026-07-23",
    totalSlots: 5,
    slots: [
      { id: 1, status: "filled", brandName: "제주항공" },
      { id: 2, status: "filled", brandName: "쏘카" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
      { id: 5, status: "reserved", brandName: "검토 중" },
    ],
    totalCost: 16000000,
    perSlotCost: 3200000,
    contentGuide: [
      "짐 꾸리기 영상 내 제품 클로즈업 노출",
      "제품 특징 캡션 언급",
      "스토리 제품 스와이프업 링크 포함",
      "릴스 댓글 고정 브랜드 멘션",
    ],
    restrictions: [
      "동일 여행 카테고리 브랜드 2개 이상 불가",
      "경쟁사 항공/렌터카 불가",
    ],
    status: "open",
    country: "jp",
  },
  {
    id: "camp-006",
    influencer: {
      name: "테크리뷰 현우",
      handle: "@tech_hyunwoo",
      platform: "youtube",
      followers: "67만",
      category: "테크 / IT",
      thumbnailUrl: "https://i.pravatar.cc/300?img=33",
      profileUrl: "https://i.pravatar.cc/300?img=33",
    },
    contentTitle: "2026 하반기 갤럭시 언박싱 + 액세서리 추천",
    contentType: "언박싱 + 리뷰",
    recruitDeadline: "2026-07-21",
    shootingDate: "2026-07-28",
    publishDate: "2026-08-02",
    totalSlots: 4,
    slots: [
      { id: 1, status: "filled", brandName: "벨킨" },
      { id: 2, status: "filled", brandName: "스피겐" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
    ],
    totalCost: 16000000,
    perSlotCost: 4000000,
    contentGuide: [
      "스마트폰 언박싱 후 액세서리 즉시 적용 장면",
      "제품 상세 기능 30초 설명",
      "영상 말미 구매 링크 고정",
    ],
    restrictions: ["삼성 공식 파트너사 경쟁 브랜드 불가"],
    status: "open",
    country: "us",
  },
  {
    id: "camp-007",
    influencer: {
      name: "청담언니",
      handle: "@청담언니",
      platform: "youtube",
      followers: "73만",
      category: "뷰티 / K-뷰티",
      thumbnailUrl: "https://yt3.googleusercontent.com/8D0xYRMWpHCKy6vgNjuzAazEuRKQeYdArJdMBI-iiPIuxhH9ASc4Xrwv2s4yeOXmbYTfCrwg=s400-c-k-c0x00ffffff-no-rj",
      profileUrl: "https://www.youtube.com/@청담언니",
    },
    contentTitle: "K-뷰티 하울 – 한국 드러그스토어 직구템",
    contentType: "샤오홍슈 노트 + 숏비디오",
    recruitDeadline: "2026-07-05",
    shootingDate: "2026-07-12",
    publishDate: "2026-07-17",
    totalSlots: 5,
    slots: [
      { id: 1, status: "filled", brandName: "아모레퍼시픽" },
      { id: 2, status: "available" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
      { id: 5, status: "reserved", brandName: "협의 중" },
    ],
    totalCost: 18000000,
    perSlotCost: 3600000,
    contentGuide: [
      "제품 사용 Before/After 비교 사진 포함",
      "한국어 + 중국어 병기 제품 설명 (사전 제공 자료 기반)",
      "샤오홍슈 노트 내 브랜드 공식 계정 태그",
      "숏비디오 1편 + 이미지 노트 2편 게시",
    ],
    restrictions: [
      "동일 카테고리 경쟁 브랜드 동시 탑승 불가",
      "광고 표기 필수 (#광고 #브랜드협찬)",
      "의약품·의료기기 카테고리 불가",
    ],
    status: "open",
    country: "cn",
  },
  {
    id: "camp-008",

    influencer: {
      name: "중국 라이프 밍밍",
      handle: "@mingming_kr_life",
      platform: "xiaohongshu",
      followers: "41만",
      category: "라이프스타일 / 음식",
      thumbnailUrl: "https://i.pravatar.cc/300?img=53",
      profileUrl: "https://i.pravatar.cc/300?img=53",
    },
    contentTitle: "한국 편의점 신상 전격 리뷰 – 중국인이 먹어봤다",
    contentType: "샤오홍슈 리뷰 노트 시리즈",
    recruitDeadline: "2026-07-15",
    shootingDate: "2026-07-22",
    publishDate: "2026-07-27",
    totalSlots: 4,
    slots: [
      { id: 1, status: "available" },
      { id: 2, status: "available" },
      { id: 3, status: "available" },
      { id: 4, status: "available" },
    ],
    totalCost: 10000000,
    perSlotCost: 2500000,
    contentGuide: [
      "제품 개봉 + 시식 리뷰 영상 (30초~1분)",
      "중국어 제품 설명 + 구매처 정보 포함",
      "한국 편의점 현장 촬영으로 진정성 강조",
      "노트 3개 + 숏비디오 1개 게시",
    ],
    restrictions: [
      "주류/담배 카테고리 불가",
      "동일 식품군 브랜드 2개 이상 불가",
    ],
    status: "open",
    country: "cn",
  },
];

export const myApplications: MyApplication[] = [
  {
    id: "app-001",
    campaignId: "camp-001",
    slotId: 3,
    status: "approved",
    appliedAt: "2026-06-18",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "멀티비타민 플러스",
    invoiceNumber: "INV-2026-001",
    invoiceIssuedAt: "2026-06-21",
    paymentDueDate: "2026-06-28",
  },
  {
    id: "app-002",
    campaignId: "camp-006",
    slotId: 3,
    status: "active",
    appliedAt: "2026-06-10",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "스마트폰 강화유리 필름",
    invoiceNumber: "INV-2026-002",
    invoiceIssuedAt: "2026-06-12",
    paymentDueDate: "2026-06-19",
    expectedPaymentDate: "2026-06-17",
  },
  {
    id: "app-003",
    campaignId: "camp-003",
    slotId: 5,
    status: "pending",
    appliedAt: "2026-06-20",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "그래놀라 바 신제품",
  },
  {
    id: "app-004",
    campaignId: "camp-007",
    slotId: 2,
    status: "completed",
    appliedAt: "2026-05-02",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "선크림 SPF50+",
    invoiceNumber: "INV-2026-003",
    invoiceIssuedAt: "2026-05-05",
    paymentDueDate: "2026-05-12",
    expectedPaymentDate: "2026-05-10",
  },
  {
    id: "app-005",
    campaignId: "camp-005",
    slotId: 3,
    status: "payment_pending",
    appliedAt: "2026-06-15",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "여행용 파우치 세트",
    invoiceNumber: "INV-2026-004",
    invoiceIssuedAt: "2026-06-19",
    paymentDueDate: "2026-06-26",
    expectedPaymentDate: "2026-06-25",
  },
  {
    id: "app-006",
    campaignId: "camp-004",
    slotId: 1,
    status: "payment_confirming",
    appliedAt: "2026-06-14",
    companyName: "(주)브랜드코리아",
    brandName: "브랜드K",
    productName: "단백질 쉐이크",
    invoiceNumber: "INV-2026-005",
    invoiceIssuedAt: "2026-06-17",
    paymentDueDate: "2026-06-24",
    expectedPaymentDate: "2026-06-22",
  },
];
